<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample data generated by Gemini 3 Flash
        $samples = [
            [
                'name' => 'Bicicletas (com esforço humano)',
                'category' => 'Vehicles',
                'ncm' => '87120010'
            ],
            [
                'name' => 'Mochilas com superfície exterior de matéria têxtil',
                'category' => 'Accessories',
                'ncm' => '42029200'
            ],
            [
                'name' => 'Camisetas (T-shirts) de algodão',
                'category' => 'Apparel',
                'ncm' => '61091000'
            ],
            [
                'name' => 'Tênis (Calçados esportivos)',
                'category' => 'Footwear',
                'ncm' => '64029110'
            ],
            [
                'name' => 'Smartphones (Celulares)',
                'category' => 'Electronics',
                'ncm' => '85171300'
            ],
            [
                'name' => 'Notebooks (Computadores portáteis)',
                'category' => 'Electronics',
                'ncm' => '84713012'
            ],
            [
                'name' => 'Café torrado e não descafeinado',
                'category' => 'Food & Beverage',
                'ncm' => '09012100'
            ],
            [
                'name' => 'Vinhos de uvas frescas',
                'category' => 'Food & Beverage',
                'ncm' => '22042100'
            ],
            [
                'name' => 'Livros, brochuras e impressos semelhantes',
                'category' => 'Editorial',
                'ncm' => '49019900'
            ],
            [
                'name' => 'Cadeiras e assentos estofados (com armação de madeira)',
                'category' => 'Furniture',
                'ncm' => '94016100'
            ]
        ];

        // Feeding the database
        foreach($samples as $sample){
            DB::table('categories')->insert([
                'name' => $sample['name'],
                'ncm' => $sample['ncm']
            ]);
        }
    }
}
