<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample data generated by Gemini 3 Flash
        $samples = [
            // Category 1: Bicicletas
            [
            'name' => 'Bicicleta Aro 29 Mountain Bike Alumínio 21V',
            'cost' => 1299.90,
            'category_id' => 1
            ],
            [
            'name' => 'Bicicleta Elétrica Urbana 350W',
            'cost' => 4500.00,
            'category_id' => 1
            ],

            // Category 2: Mochilas
            [
            'name' => 'Mochila Impermeável para Notebook Urbana',
            'cost' => 189.90,
            'category_id' => 2
            ],
            [
            'name' => 'Mochila de Camping cargueira 65L',
            'cost' => 349.00,
            'category_id' => 2
            ],

            // Category 3: Camisetas
            [
            'name' => 'Camiseta Algodão Egípcio Básica Preta',
            'cost' => 79.90,
            'category_id' => 3
            ],
            [
            'name' => 'Kit 3 Camisetas Masculinas Casual Lisa',
            'cost' => 119.00,
            'category_id' => 3
            ],

            // Category 4: Tênis
            [
            'name' => 'Tênis Esportivo para Corrida Amortecedor',
            'cost' => 299.99,
            'category_id' => 4
            ],

            // Category 5: Smartphones
            [
            'name' => 'Smartphone 5G 128GB 8GB RAM Tela 6.5',
            'cost' => 1850.00,
            'category_id' => 5
            ],

            // Category 6: Notebooks
            [
            'name' => 'Notebook Intel i5 16GB RAM SSD 512GB',
            'cost' => 3200.00,
            'category_id' => 6
            ],

            // Category 7: Café
            [
            'name' => 'Café Gourmet Moído 100% Arábica 500g',
            'cost' => 32.50,
            'category_id' => 7
            ],

            // Category 8: Vinhos
            [
            'name' => 'Vinho Tinto Seco Cabernet Sauvignon 750ml',
            'cost' => 68.90,
            'category_id' => 8
            ],

            // Category 9: Livros
            [
            'name' => 'Livro: O Guia do Mochileiro das Galáxias',
            'cost' => 42.00,
            'category_id' => 9
            ],

            // Category 10: Cadeiras e assentos
            [
            'name' => 'Cadeira de Jantar de Madeira Estofada',
            'cost' => 245.00,
            'category_id' => 10
            ]
        ];


        // Feeding the database
        foreach($samples as $sample){
            DB::table('products')->insert([
                'name' => $sample['name'],
                'cost' => $sample['cost'],
                'category_id' => $sample['category_id']
            ]);
        }

    } // end of run
} // end of seeder
