export function formatFloat(imaskString){
    if(!imaskString){ return 0.0; }

    let cleaned = imaskString.replace(/[^\d.,]/g,'');
    cleaned.replace(',' , '.');
    const result = parseFloat(cleaned);

    if(isNaN(result)){
        return 0.0;
    } else {
        return result;
    }
}

export function formatInt(imaskString){
    if(!imaskString){ return 0.0; }

    return parseInt(imaskString);
}

/**
 * 1. Calculate Sell Price
 */
function calculateSellPrice(cost, tax, fee, margin) {
    const divisor = 1 - tax - fee - margin;
    if (divisor <= 0) {
        throw new Error("Invalid inputs: Combined deductions (tax + fee + margin) must be less than 100%.");
    }
    return roundTo(cost / divisor, 2); // Currency usually 2 decimals
}

/** -------------------------------------
 *  FUNCTIONS GENERATED BY GEMINI 3 FLASH
 * -------------------------------------/

/**
 * Helper to fix floating-point math issues.
 * @param {number} value - The number to round.
 * @param {number} decimals - Number of decimal places (default 4 for percentages/rates).
 */
const roundTo = (value, decimals = 4) => {
    return Number(Math.round(value + 'e' + decimals) + 'e-' + decimals);
};

/**
 * 2. Calculate Product Cost
 */
function calculateProductCost(sell, tax, fee, margin) {
    if (sell <= 0) throw new Error("Sell price must be greater than 0.");
    return roundTo(sell * (1 - tax - fee - margin), 2);
}

/**
 * 3. Calculate Tax Rate
 */
function calculateTaxFee(sell, cost, fee, margin) {
    if (sell <= 0) throw new Error("Sell price must be greater than 0 to calculate rates.");
    return roundTo(1 - fee - margin - (cost / sell), 4);
}

/**
 * 4. Calculate Marketplace Fee Rate
 */
function calculateMarketplaceFee(sell, cost, tax, margin) {
    if (sell <= 0) throw new Error("Sell price must be greater than 0 to calculate rates.");
    return roundTo(1 - tax - margin - (cost / sell), 4);
}

/**
 * 5. Calculate Profit Margin Rate
 */
function calculateProfitMargin(sell, cost, tax, fee) {
    if (sell <= 0) throw new Error("Sell price must be greater than 0 to calculate rates.");
    return roundTo(1 - tax - fee - (cost / sell), 4);
}